evolving: False # If false Model does not considere links that appeared in previous timestamp
one_hot: True
name: DCRNN
score: 'none'
pred_next: False
clip_grad: False

link_pred:
  _target_: dgt.models.DCRNN
  num_nodes: ${dataset.num_nodes}
  num_features: ${dataset.features_dim}
  in_channels: 128
  window: 3
  K: 2
  bias: true
  one_hot: ${model.one_hot}
  undirected: False