evolving: False # If false Model does not considere links that appeared in previous timestamp
one_hot: True
name: EdgeBank
pred_next: False
clip_grad: False
score: 'none'

link_pred:
  _target_: tw_benchmark.models.EdgeBank
  window: 3
  undirected: True 
  