
name: DPPIN-Ho
datadir: /users/k/karmimy/These/DynamicGraphTransformer/DPPIN
num_nodes: 1548
num_edges: 42220
timestamp: 36
features_dim: ${dataset.timestamp}

num_classes: 2 # 2 nodes classes for DPPIN-Ito
dts: 
  node_classif: 
    train:
      _target_: tw_benchmark.datasets.ClassifData
      datadir: ${dataset.datadir}
      dataname: ${dataset.name}
      mode: train
      evolving: ${model.evolving}
      n_nodes: ${dataset.num_nodes}
      one_hot: ${model.one_hot}


    test: 
      _target_: tw_benchmark.datasets.ClassifData
      datadir: ${dataset.datadir}
      dataname: ${dataset.name}
      mode: test
      evolving: ${model.evolving}
      n_nodes: ${dataset.num_nodes}
      one_hot: ${model.one_hot}
  
  link_pred:
    _target_: tw_benchmark.datasets.LinkPredData
    datadir: ${dataset.datadir}
    dataname: ${dataset.name}
    evolving: ${model.evolving}
    n_nodes: ${dataset.num_nodes}
    one_hot: ${model.one_hot}
    sampling: ${task.sampling}
    train_ratio : ${task.train_ratio}
    split: ${task.split}
    pred_next : ${model.pred_next}


  

